import { Barlow } from 'next/font/google'
import './globals.css'
import '../assets/css/base.css'



const barlow = Barlow({
   subsets: ['latin'], 
   weight: '400',
  
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  )
}
